#!/usr/bin/env bash
echo "
===============
|  Running detekt...
===============
"

./gradlew detekt

status=$?

if [ "$status" = 0 ] ; then
    echo "이슈 없음"
    exit 0
else
    echo 1>&2 "이슈 있음"
    exit 1
fi